module.exports = {
  SCHOOL_CHANGE_INFO: 'SCHOOL_CHANGE_INFO',
  SCHOOL_REQUEST_CLASS: 'SCHOOL_REQUEST_CLASS',
  SCHOOL_ACCEPT_CLASS: 'SCHOOL_ACCEPT_CLASS',
  SCHOOL_REJECT_CLASS: 'SCHOOL_REJECT_CLASS',
  SCHOOL_REMOVE_CLASS: 'SCHOOL_REMOVE_CLASS',
  SCHOOL_REMOVE_USER: 'SCHOOL_REMOVE_USER'
};
