module.exports = {
  CLASS_CHANGE_INFO: 'CLASS_CHANGE_INFO',
  CLASS_DEACTIVATE_USER: 'CLASS_DEACTIVATE_USER',
  CLASS_ACTIVATE_USER: 'CLASS_ACTIVATE_USER',
  CLASS_ACCEPT_USER: 'CLASS_ACCEPT_USER',
  CLASS_REJECT_USER: 'CLASS_REJECT_USER',
  CLASS_CANCEL_INVITATION_USER: 'CLASS_CANCEL_INVITATION_USER',
  CLASS_REMOVE_USER: 'CLASS_REMOVE_USER',
  CLASS_DELETED: 'CLASS_DELETED',
  CLASS_DUPLICATED: 'CLASS_DUPLICATED'
};
