module.exports = {
  CLASS_CHANGE_INFO: 'CLASS_CHANGE_INFO',
  CLASS_DEACTIVATE_USER: 'CLASS_DEACTIVATE_USER',
  CLASS_ACTIVATE_USER: 'CLASS_ACTIVATE_USER',
  CLASS_ACCEPT_USER: 'CLASS_ACCEPT_USER',
  CLASS_REJECT_USER: 'CLASS_REJECT_USER',
  CLASS_CANCEL_INVITATION_USER: 'CLASS_CANCEL_INVITATION_USER',
  CLASS_REMOVE_USER: 'CLASS_REMOVE_USER',
  CLASS_DELETED: 'CLASS_DELETED',
  CLASS_DUPLICATED: 'CLASS_DUPLICATED',
  SCHOOL_CHANGE_INFO: 'SCHOOL_CHANGE_INFO',
  SCHOOL_REQUEST_CLASS: 'SCHOOL_REQUEST_CLASS',
  SCHOOL_ACCEPT_CLASS: 'SCHOOL_ACCEPT_CLASS',
  SCHOOL_REJECT_CLASS: 'SCHOOL_REJECT_CLASS',
  SCHOOL_REMOVE_CLASS: 'SCHOOL_REMOVE_CLASS',
  SCHOOL_REMOVE_USER: 'SCHOOL_REMOVE_USER'
};
