image: keymetrics/pm2:6

cache:
  paths:
    - node_modules/

stages:
  - deploy

deploy_dev:
  stage: deploy
  before_script:
    - apk update && apk upgrade
    - apk add git openssh bash
    - mkdir -p ~/.ssh
    - echo $DEPLOY_KEY | base64 -d > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
    - ssh -o StrictHostKeyChecking=no -T "$DEPLOY_USER@$DEPLOY_HOST"
  script:
    - pm2 deploy ecosystem.config.js development setup 2>&1 || true
    - pm2 deploy ecosystem.config.js development
  environment:
    name: development
  only:
    - dev

deploy_prod:
  stage: deploy
  before_script:
    - apk update && apk upgrade
    - apk add git openssh bash
    - mkdir -p ~/.ssh
    - echo $DEPLOY_KEY | base64 -d > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
    - ssh -o StrictHostKeyChecking=no -T "$DEPLOY_USER@$DEPLOY_HOST"
  script:
    - pm2 deploy ecosystem.config.js production setup 2>&1 || true
    - pm2 deploy ecosystem.config.js production
  environment:
    name: production
  only:
    - master
