image: node:latest

stages:
  - build
  - deploy

build_dev: # A job to build the static website - replace it with your build methods
  image: weltn24/up-docker-node-chrome-headless
  stage: build
  variables:
    FILE_NAME: sfh-dev.zip
  before_script:
    - apt-get install zip unzip
  script:
    - npm install
    - CI=false npm run build
    - cd build; zip -r ../${FILE_NAME} .
  artifacts:
    paths:
      - ${FILE_NAME} # This is what we want to publish, replace with your `dist` directory
  only:
    - dev

deploy_dev:
  stage: deploy
  variables:
    DEPLOY_USER: deploy
    DEPLOY_HOST: 144.91.77.116
    DEPLOY_PATH: /var/www/karpadev.karpalabs.com/public_html/sfh-dev/
    FILE_NAME: sfh-dev.zip
    ZIP_PATH: /home/$DEPLOY_USER/$FILE_NAME
    ENV_NAME: dev
    ENV_URL: https://karpadev.karpalabs.com/sfh-dev
  before_script:
    - apt-get update -qq
    - apt-get install -qq git
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "${SSH_PRIVATE_KEY}")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh ${DEPLOY_USER}@${DEPLOY_HOST} rm -rf ${DEPLOY_PATH}*
    - ssh ${DEPLOY_USER}@${DEPLOY_HOST} rm -rf ${ZIP_PATH}${FILE_NAME}
    - scp ${FILE_NAME} ${DEPLOY_USER}@${DEPLOY_HOST}:${ZIP_PATH}
    - ssh ${DEPLOY_USER}@${DEPLOY_HOST} unzip -o ${FILE_NAME} -d ${DEPLOY_PATH}
    - ssh ${DEPLOY_USER}@${DEPLOY_HOST} 'sed -i "s/\/assets/\/sfh-dev\/assets/g" /var/www/karpadev.karpalabs.com/public_html/sfh-dev/static/css/main.*.chunk.css'
  environment:
    name: ${ENV_NAME}
    url: ${ENV_URL}
  only:
    - dev
