// GLOBAL
export const SET_LOADER = 'SET_LOADER';

// LOGIN
export const SET_LOGIN = 'SET_LOGIN';
export const SET_LOGIN_FAILED = 'SET_LOGIN_FAILED';
export const SET_CLOSE_ALERT = 'SET_CLOSE_ALERT';
export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS';
export const SET_RESEND_ACTIVATION = 'SET_RESEND_ACTIVATION';
export const CONFIRM_LOGIN = 'CONFIRM_LOGIN';
export const SET_MODAL_FORM_LOGIN = 'SET_MODAL_FORM_LOGIN';
export const SET_CONFIRM_LOGIN = 'SET_CONFIRM_LOGIN';
export const SET_CONFIRM_LOGIN_SUCCESS = 'SET_CONFIRM_LOGIN_SUCCESS';
export const SET_ROLES_SUCCESS = 'SET_ROLES_SUCCESS';
export const SET_CLOSE_REGIST_ALERT = 'SET_CLOSE_REGIST_ALERT';
export const SET_SPINNER = 'SET_SPINNER';
export const SET_REGISTER = 'SET_REGISTER';
export const SET_REGISTER_SUCCESS = 'SET_REGISTER_SUCCESS';
export const SET_REGISTER_FAILED = 'SET_REGISTER_FAILED';
export const SET_RESEND_ACTIVATION_REGIST = 'SET_RESEND_ACTIVATION_REGIST';
export const SET_MODAL_ACTIVATION = 'SET_MODEL_ACTIVATION';
export const SET_FORGOT = 'SET_FORGOT';
export const SET_FORGOT_SUCCESS = 'SET_FORGOT_SUCCESS';
export const SET_FORGOT_RETYPE = 'SET_FORGOT_RETYPE';
export const SET_FORGOT_SUCCESS_RETYPE = 'SET_FORGOT_SUCCESS_RETYPE';
export const ON_CHANGE_STATE_LOGIN = 'ON_CHANGE_STATE_LOGIN';
export const ON_CHANGE_STATE_FORGOT = 'ON_CHANGE_STATE_FORGOT';
export const ON_CHANGE_STATE_REGISTER = 'ON_CHANGE_STATE_REGISTER';
export const RESET_STATE_LOGIN = 'RESET_STATE_LOGIN';
export const GET_BRANCH = 'GET_BRANCH';
export const GET_BRANCH_SUCCESS = 'GET_BRANCH_SUCCESS';
export const EMAIL_ACTIVATION = 'EMAIL_ACTIVATION';
export const EMAIL_ACTIVATION_SUCCESS = 'EMAIL_ACTIVATION_SUCCESS';
export const GET_TOKEN = 'GET_TOKEN';
export const SET_TOKEN_SUCCESS = 'SET_TOKEN_SUCCESS';
export const SET_LOGOUT = 'SET_LOGOUT';
export const SET_NEW_PASSWORD = 'SET_NEW_PASSWORD';
export const SET_NEW_PASSWORD_SUCCESS = 'SET_NEW_PASSWORD_SUCCESS';
export const ON_CHANGE_STATE_NEW_PASSWORD = 'ON_CHANGE_STATE_NEW_PASSWORD';
export const ON_CHANGE_STATE_UPDATE_PASSWORD = 'ON_CHANGE_STATE_UPDATE_PASSWORD';
export const SET_UPDATE_PASSWORD = 'SET_UPDATE_PASSWORD';
export const SET_UPDATE_PASSWORD_CODE = 'SET_UPDATE_PASSWORD_CODE';
export const SET_GOOGLE_LOGIN = 'SET_GOOGLE_LOGIN';

//profile
export const REQUEST_USER_DATA = 'REQUEST_USER_DATA';
export const GET_USER_DATA = 'GET_USER_DATA';
export const SET_PROFILE = 'SET_PROFILE';
export const SET_PROFILE_SUCCESS = 'SET_PROFILE_SUCCESS';
export const SET_PROFILE_FAILED = 'SET_PROFILE_FAILED';
export const ON_CHANGE_STATE_PROFILE = ' ON_CHANGE_STATE_PROFILE';
export const ON_CHANGE_STATE_EDIT_PROFILE = 'ON_CAHNGE_STATE_EDIT_PROFILE';
export const SET_UPDATE_PASSWORD_PROFILE = 'SET_UPDATE_PASSWORD_PROFILE';

//SCHOOL INFO
export const GET_SCHOOL = 'GET_SCHOOL';
export const SET_SCHOOL_DATA = 'SET_SCHOOL_DATA';
export const SET_SCHOOL_AUTHORITY = 'SET_SCHOOL_AUTHORITY';
export const SET_SCHOOL_MODAL = 'SET_SCHOOL_MODAL';
export const ON_UPDATE_SCHOOL = 'ON_UPDATE_SCHOOL';
export const SAVE_UPDATE_SCHOOL = 'SAVE_UPDATE_SCHOOL';
export const UPDATE_SCHOOL_SPINNER = 'UPDATE_SCHOOL_SPINNER';
export const SUCCESS_UPDATE_SCHOOL = 'SUCCESS_UPDATE_SCHOOL';
export const DONE_UPDATE_SCHOOL = 'DONE_UPDATE_SCHOOL';
export const FAILED_UPDATE_SCHOOL = 'FAILED_UPDATE_SCHOOL';
export const DELETE_SCHOOL = 'DELETE_SCHOOL';
export const DELETE_SCHOOL_FAILED = 'DELETE_SCHOOL_FAILED';
export const REMOVE_SCHOOL_DATA = 'REMOVE_SCHOOL_DATA';
export const GET_SCHOOL_CLASS = 'GET_SCHOOL_CLASS';
export const SET_LIST_CLASS = 'SET_LIST_CLASS';
export const CONNECT_CLASS_FROM_SCHOOL = 'CONNECT_CLASS_FROM_SCHOOL';
export const SET_CONNECT_CLASS = 'SET_CONNECT_CLASS';
export const SUCCESS_CONNECT_CLASS = 'SUCCESS_CONNECT_CLASS';
export const FAILED_CONNECT_CLASS = 'FAILED_CONNECT_CLASS';
export const SET_MODAL_CREATE_SCHOOL_CLASS = 'SET_MODAL_CREATE_SCHOOL_CLASS';
export const CLOSE_MODAL_CONNECT_CLASS = 'CLOSE_MODAL_CONNECT_CLASS';
export const SCHOOL_CREATE_CLASS = 'SCHOOL_CREATE_CLASS';
export const SUCCESS_CREATE_SCHOOL_CLASS = 'SUCCESS_CREATE_SCHOOL_CLASS';
export const FAILED_CREATE_SCHOOL_CLASS = 'FAILED_CREATE_SCHOOL_CLASS';
export const CHANGE_LINK_STATUS = 'CHANGE_LINK_STATUS';
export const CLOSE_SCHOOL_SUCCESS_MODAL = 'CLOSE_SCHOOL_SUCCESS_MODAL';
export const DECLINE_JOIN_SCHOOL = 'DECLINE_JOIN_SCHOOL';
export const APPROVE_JOIN_SCHOOL = 'APPROVE_JOIN_SCHOOL';
export const SET_FILTER = 'SET_FILTER';
export const SEARCH_CLASS = 'SEARCH_CLASS';
export const SET_FILTERED_CLASS = 'SET_FILTERED_CLASS';
export const GET_SCHOOL_MEMBERS = 'GET_SCHOOL_MEMBERS';
export const CHANGE_SCHOOL_OWNER = 'CHANGE_SCHOOL_OWNER';
export const SET_MODAL_ADD_SCHOOL_MEMBER = 'SET_MODAL_ADD_SCHOOL_MEMBER';
export const REMOVE_SCHOOL_MEMBER = 'REMOVE_SCHOOL_MEMBER';
export const SET_SCHOOL_MEMBERS = 'SET_SCHOOL_MEMBERS';
export const FAILED_CHANGE_OWNER = 'FAILED_CHANGE_OWNER';
export const SUCCESS_CHANGE_OWNER = 'SUCCESS_CHANGE_OWNER';
export const SUCCESS_DELETE_MEMBER = 'SUCCESS_DELETE_MEMBER';
export const ADD_SCHOOL_MEMBER = 'ADD_SCHOOL_MEMBER';
export const SUCCESS_ADD_MEMBER = 'SUCCESS_ADD_MEMBER';
export const FAILED_ADD_MEMBER = 'FAILED_ADD_MEMBER';

//Class
export const SET_CLASS_INFO = 'SET_CLASS_INFO';
export const SET_CLASS_INFO_DATA = 'SET_CLASS_INFO_DATA';
export const ON_CHANGE_STATE_CLASS_INFO = 'ON_CHANGE_STATE_CLASS_INFO';
export const ON_CHANGE_STATE_EDIT_CLASS = 'ON_CHANGE_STATE_EDIT_CLASS';

export const SET_CLASS_MEMBERS = 'SET_CLASS_MEMBERS';
export const SET_CLASS_MEMBERS_DATA = 'SET_CLASS_MEMBERS_DATA';
export const ON_CHANGE_STATE_CLASS_MEMBERS = 'ON_CHANGE_STATE_CLASS_MEMBERS';

export const SET_CLASS_DELETE = 'SET_CLASS_DELETE';
export const SET_DELETE_CLASS_SUCCESS = 'SET_DELETE_CLASS_SUCCESS';
export const SET_DELETE_CLASS_FAIL = 'SET_DELETE_CLASS_FAIL';

export const UPDATE_CLASS_INFO = 'UPDATE_CLASS_INFO';
export const SET_UPDATE_CLASS_SUCCESS = 'SET_UPDATE_CLASS_SUCCESS';
export const SET_UPDATE_CLASS_FAIL = 'SET_UPDATE_CLASS_FAIL';

export const SET_CLASS_DUPLICATE = 'SET_CLASS_DUPLICATE';
export const SET_DUPLICATE_CLASS_SUCCESS = 'SET_DUPLICATE_CLASS_SUCCESS';
export const SET_DUPLICATE_CLASS_FAIL = 'SET_DUPLICATE_CLASS_FAIL';

export const ON_CHANGE_STATE_UPDATE_MEMBER = 'ON_CHANGE_STATE_UPDATE_MEMBER';
export const SET_UPDATE_MEMBER = 'SET_UPDATE_MEMBER';
export const SET_UPDATE_MEMBER_SUCCESS = 'SET_UPDATE_MEMBER_SUCCESS';
export const SET_UPDATE_MEMBER_FAIL = 'SET_UPDATE_MEMBER_FAIL';

export const ON_CHANGE_STATE_ADD_MEMBER = 'ON_CHANGE_STATE_ADD_MEMBER';
export const SET_ADD_MEMBER = 'SET_ADD_MEMBER';
export const SET_ADD_MEMBER_SUCCESS = 'SET_ADD_MEMBER_SUCCESS';
export const SET_ADD_MEMBER_FAIL = 'SET_ADD_MEMBER_FAIL';

// Get Products
export const FETCH_PRODUCTS_BEGIN = 'FETCH_PRODUCTS_BEGIN';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT';

// FILTERS
export const FILTER_BRAND = 'FILTER_BRAND';
export const FILTER_COLOR = 'FILTER_COLOR';
export const FILTER_PRICE = 'FILTER_PRICE';
export const SORT_BY = 'SORT_BY';

export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';

// Cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREMENT_QTY = 'INCREMENT_QTY';
export const DECREMENT_QTY = 'DECREMENT_QTY';

// WishList
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';

// Compare
export const ADD_TO_COMPARE = 'ADD_TO_COMPARE';
export const REMOVE_FROM_COMPARE = 'REMOVE_FROM_COMPARE';

// CheckOut Process
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE';

// task siswa
export const SET_DATE = 'SET_DATE';
export const SET_MODAL = 'SET_MODAL';
export const STUDENT_GET_TASK_LIST = 'STUDENT_GET_TASK_LIST';
export const GET_TASK_SISWA_LIST_SUCCESS = 'GET_TASK_SISWA_LIST_SUCCESS';
export const SET_UPLOAD_TASK_SISWA = 'SET_UPLOAD_TASK_SISWA';
export const SET_TASK_LIST_FILTER = 'SET_TASK_LIST_FILTER';
export const STUDENT_PUT_COLLECTION = 'STUDENT_PUT_COLLECTION';
export const STUDENT_PUT_COLLECTION_SUCCESS = 'STUDENT_PUT_COLLECTION_SUCCESS';
export const STUDENT_PUT_COLLECTION_FILES = 'STUDENT_PUT_COLLECTION_FILES';
export const STUDENT_SUBMIT_COLLECTION = 'STUDENT_SUBMIT_COLLECTION';
export const STUDENT_GET_TASK_FILE_LIST = 'STUDENT_GET_TASK_FILE_LIST';
export const STUDENT_GET_TASK_FILE_LIST_SUCCESS = 'STUDENT_GET_TASK_FILE_LIST_SUCCESS';
export const STUDENT_GET_UPLOADED_FILE_LIST = 'STUDENT_GET_UPLOADED_FILE_LIST';
export const STUDENT_GET_UPLOADED_FILE_LIST_SUCCESS = 'STUDENT_GET_UPLOADED_FILE_LIST_SUCCESS';
export const STUDENT_DOWNLOAD_FILE = 'STUDENT_DOWNLOAD_FILE';
export const SET_MODAL_FORM_DOWNLOAD = 'SET_MODAL_FORM_DOWNLOAD';

//ortu
export const GET_TASK_ORTU_LIST = 'GET_TASK_ORTU_LIST';
export const GET_TASK_ORTU_LIST_SUCCESS = 'GET_TASK_ORTU_LIST_SUCCESS';

//guru
export const SET_URL_PATH = 'SET_URL_PATH';
export const DELETE_TASK = 'DELETE_TASK';
export const SET_STATE_TASK_DETAIL = 'SET_STATE_TASK_DETAIL';
export const HANDLE_STATE_UPDATE_TASK = 'HANDLE_STATE_UPDATE_TASK';
export const GET_TASK_GURU_LIST = 'GET_TASK_GURU_LIST';
export const GET_TASK_GURU_LIST_SUCCESS = 'GET_TASK_GURU_LIST_SUCCESS';
export const GURU_GET_TASK_COLLECTION_LIST = 'GURU_GET_TASK_COLLECTION_LIST';
export const GURU_GET_TASK_COLLECTION_LIST_SUCCESS = 'GURU_GET_TASK_COLLECTION_LIST_SUCCESS';
export const GURU_GET_UPLOADED_COLLECTION_LIST = 'GURU_GET_UPLOADED_COLLECTION_LIST';
export const GURU_GET_UPLOADED_COLLECTION_LIST_SUCCESS = 'GURU_GET_UPLOADED_COLLECTION_LIST_SUCCESS';
export const GET_SUBJECT_LIST = 'GET_SUBJECT_LIST';
export const GET_SUBJECT_LIST_SUCCESS = 'GET_SUBJECT_LIST_SUCCESS';
export const GET_CLASS_LIST = 'GET_CLASS_LIST';
export const GET_CLASS_LIST_SUCCESS = 'GET_CLASS_LIST_SUCCESS';
export const SET_MODAL_FORM = 'SET_MODAL_FORM';
export const SET_MODAL_EDIT_FORM_GURU = 'SET_MODAL_EDIT_FORM_GURU';
export const GURU_DOWNLOAD_COLLECTION = 'GURU_DOWNLOAD_COLLECTION';
export const SET_STATE_MODAL_FORM_UPLOADED_COLLECTION = 'SET_STATE_MODAL_FORM_UPLOADED_COLLECTION';
export const POST_TASK = 'POST_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const ARCHIVED_TASK = 'ARCHIVED_TASK';
export const GURU_DELETE_TASK_FILE = 'GURU_DELETE_TASK_FILE';
export const GET_TASK_GURU_BY_ID = 'GET_TASK_GURU_BY_ID';

//kepsek
export const KEPSEK_GET_TASK_COLLECTION_LIST = 'KEPSEK_GET_TASK_COLLECTION_LIST';
export const KEPSEK_GET_TASK_COLLECTION_LIST_SUCCESS = 'KEPSEK_GET_TASK_COLLECTION_LIST_SUCCESS';
export const KEPSEK_GET_TASK_LIST = 'KEPSEK_GET_TASK_LIST';
export const KEPSEK_GET_TASK_LIST_SUCCESS = 'KEPSEK_GET_TASK_LIST_SUCCESS';
export const KEPSEK_GET_SUBJECT_LIST = 'KEPSEK_GET_SUBJECT_LIST';
export const KEPSEK_GET_SUBJECT_LIST_SUCCESS = 'KEPSEK_GET_SUBJECT_LIST_SUCCESS';
export const KEPSEK_GET_CLASS_LIST = 'KEPSEK_GET_CLASS_LIST';
export const KEPSEK_GET_CLASS_LIST_SUCCESS = 'KEPSEK_GET_CLASS_LIST_SUCCESS';
export const KEPSEK_GET_UPLOADED_COLLECTION_LIST = 'KEPSEK_GET_UPLOADED_COLLECTION_LIST';
export const KEPSEK_GET_UPLOADED_COLLECTION_LIST_SUCCESS = 'KEPSEK_GET_UPLOADED_COLLECTION_LIST_SUCCESS';
export const KEPSEK_DOWNLOAD_COLLECTION = 'KEPSEK_DOWNLOAD_COLLECTION';

//admin
export const ADMIN_GET_GROUP_LIST = 'ADMIN_GET_GROUP_LIST';
export const ADMIN_GET_GROUP_LIST_SUCCESS = 'ADMIN_GET_GROUP_LIST_SUCCESS';
export const ADMIN_GET_USER_LIST = 'ADMIN_GET_USER_LIST';
export const ADMIN_GET_USER_LIST_SUCCESS = 'ADMIN_GET_USER_LIST_SUCCESS';
export const ADMIN_GET_CLASS_LIST = 'ADMIN_GET_CLASS_LIST';
export const ADMIN_GET_CLASS_LIST_SUCCESS = 'ADMIN_GET_CLASS_LIST_SUCCESS';
export const ADMIN_GET_SUBJECT_LIST = 'ADMIN_GET_SUBJECT_LIST';
export const ADMIN_GET_SUBJECT_LIST_SUCCESS = 'ADMIN_GET_SUBJECT_LIST_SUCCESS';
export const ADMIN_GET_STUDENT_LIST = 'ADMIN_GET_STUDENT_LIST';
export const ADMIN_GET_STUDENT_LIST_SUCCESS = 'ADMIN_GET_STUDENT_LIST_SUCCESS';
export const ADMIN_GET_ROLE_LIST = 'ADMIN_GET_ROLE_LIST';
export const ADMIN_GET_ROLE_LIST_SUCCESS = 'ADMIN_GET_ROLE_LIST_SUCCESS';
export const ADMIN_GET_ROLE_BY_USER_ID = 'ADMIN_GET_ROLE_BY_USER_ID';
export const ADMIN_GET_USER_BY_ID = 'ADMIN_GET_USER_BY_ID';
export const ADMIN_GET_DATASOURCE_CLASS = 'ADMIN_GET_DATASOURCE_CLASS';
export const ADMIN_GET_DATASOURCE_CLASS_SUCCESS = 'ADMIN_GET_DATASOURCE_CLASS_SUCCESS';
export const ADMIN_GET_DATASOURCE_GROUP = 'ADMIN_GET_DATASOURCE_GROUP';
export const ADMIN_GET_DATASOURCE_GROUP_SUCCESS = 'ADMIN_GET_DATASOURCE_GROUP_SUCCESS';
export const ADMIN_GET_DATASOURCE_SUBJECT = 'ADMIN_GET_DATASOURCE_SUBJECT';
export const ADMIN_GET_DATASOURCE_SUBJECT_SUCCESS = 'ADMIN_GET_DATASOURCE_SUBJECT_SUCCESS';
export const ADMIN_GET_DATASOURCE_STUDENT = 'ADMIN_GET_DATASOURCE_STUDENT';
export const ADMIN_GET_DATASOURCE_STUDENT_SUCCESS = 'ADMIN_GET_DATASOURCE_STUDENT_SUCCESS';
export const ADMIN_SET_MODAL_FORM_USER = 'ADMIN_SET_MODAL_FORM_USER';
export const ADMIN_SET_MODAL_FORM_USER_ROLE = 'ADMIN_SET_MODAL_FORM_USER_ROLE';
export const ADMIN_SET_MODAL_FORM_GROUP = 'ADMIN_SET_MODAL_FORM_GROUP';
export const ADMIN_SET_MODAL_FORM_CLASS = 'ADMIN_SET_MODAL_FORM_CLASS';
export const ADMIN_SET_MODAL_FORM_SUBJECT = 'ADMIN_SET_MODAL_FORM_SUBJECT';
export const ADMIN_SET_MODAL_FORM_STUDENT = 'ADMIN_SET_MODAL_FORM_STUDENT';
export const ADMIN_CREATE_USER = 'ADMIN_CREATE_USER';
export const ADMIN_CREATE_CLASS = 'ADMIN_CREATE_CLASS';
export const ADMIN_CREATE_SUBJECT = 'ADMIN_CREATE_SUBJECT';
export const ADMIN_CREATE_STUDENT = 'ADMIN_CREATE_STUDENT';
export const ADMIN_SIGN_USER_ROLE = 'ADMIN_SIGN_USER_ROLE';
