// GLOBAL
export const SET_LOADER = "SET_LOADER"

// LOGIN
export const SET_LOGIN = "SET_LOGIN"
export const SET_LOGIN_SUCCESS = "SET_LOGIN_SUCCESS"
export const SET_REGISTER = "SET_REGISTER"
export const SET_REGISTER_SUCCESS = "SET_REGISTER_SUCCESS"
export const SET_FORGOT = "SET_FORGOT"
export const SET_FORGOT_SUCCESS = "SET_FORGOT_SUCCESS"
export const SET_FORGOT_RETYPE = "SET_FORGOT_RETYPE"
export const SET_FORGOT_SUCCESS_RETYPE = "SET_FORGOT_SUCCESS_RETYPE"
export const ON_CHANGE_STATE_LOGIN = "ON_CHANGE_STATE_LOGIN"
export const ON_CHANGE_STATE_FORGOT = "ON_CHANGE_STATE_FORGOT"
export const ON_CHANGE_STATE_REGISTER = "ON_CHANGE_STATE_REGISTER"
export const RESET_STATE_LOGIN = "RESET_STATE_LOGIN"
export const GET_BRANCH = "GET_BRANCH"
export const GET_BRANCH_SUCCESS = "GET_BRANCH_SUCCESS"
export const EMAIL_ACTIVATION = "EMAIL_ACTIVATION"
export const EMAIL_ACTIVATION_SUCCESS = "EMAIL_ACTIVATION_SUCCESS"
export const GET_TOKEN = "GET_TOKEN"
export const SET_TOKEN_SUCCESS = "SET_TOKEN_SUCCESS"
export const SET_LOGOUT = "SET_LOGOUT"

// Get Products
export const FETCH_PRODUCTS_BEGIN = 'FETCH_PRODUCTS_BEGIN'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT'

// FILTERS
export const FILTER_BRAND = 'FILTER_BRAND'
export const FILTER_COLOR = 'FILTER_COLOR'
export const FILTER_PRICE = 'FILTER_PRICE'
export const SORT_BY = 'SORT_BY'

export const CHANGE_CURRENCY = 'CHANGE_CURRENCY'


// Cart
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const INCREMENT_QTY = 'INCREMENT_QTY'
export const DECREMENT_QTY = 'DECREMENT_QTY'



// WishList
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST'
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST'


// Compare
export const ADD_TO_COMPARE = 'ADD_TO_COMPARE'
export const REMOVE_FROM_COMPARE = 'REMOVE_FROM_COMPARE'



// CheckOut Process
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'

// task siswa
export const SET_DATE = 'SET_DATE'
export const SET_MODAL = 'SET_MODAL'
export const GET_TASK_SISWA_LIST = 'GET_TASK_SISWA_LIST'
export const GET_TASK_SISWA_LIST_SUCCESS = 'GET_TASK_SISWA_LIST_SUCCESS'
export const SET_UPLOAD_TASK_SISWA = 'SET_UPLOAD_TASK_SISWA'
export const SET_TASK_LIST_FILTER = 'SET_TASK_LIST_FILTER'

export const GET_TASK_ORTU_LIST = 'GET_TASK_ORTU_LIST'
export const GET_TASK_ORTU_LIST_SUCCESS = 'GET_TASK_ORTU_LIST_SUCCESS'

//guru
export const DELETE_TASK = 'DELETE_TASK'
export const SET_STATE_TASK_DETAIL = 'SET_STATE_TASK_DETAIL'
export const HANDLE_STATE_UPDATE_TASK = 'HANDLE_STATE_UPDATE_TASK'
export const GET_TASK_GURU_LIST = 'GET_TASK_GURU_LIST'
export const GET_TASK_GURU_LIST_SUCCESS = 'GET_TASK_GURU_LIST_SUCCESS'
export const GET_SUBJECT_LIST = 'GET_SUBJECT_LIST'
export const GET_SUBJECT_LIST_SUCCESS = 'GET_SUBJECT_LIST_SUCCESS'
export const GET_CLASS_LIST = 'GET_CLASS_LIST'
export const GET_CLASS_LIST_SUCCESS = 'GET_CLASS_LIST_SUCCESS'
export const SET_MODAL_FORM = 'SET_MODAL_FORM'
export const POST_TASK = 'POST_TASK'
